torque_limit = {
    "left_hip_pitch_joint": 230.0,
    "left_hip_roll_joint": 160.0,
    "left_hip_yaw_joint": 105.0,
    "left_knee_joint": 280.0,
    "left_ankle_pitch_joint": 80.0,
    "left_ankle_roll_joint": 80.0,
    "right_hip_pitch_joint": 230.0,
    "right_hip_roll_joint": 160.0,
    "right_hip_yaw_joint": 105.0,
    "right_knee_joint": 280.0,
    "right_ankle_pitch_joint": 80.0,
    "right_ankle_roll_joint": 80.0,
    "waist_roll_joint": 150.0,
    "waist_pitch_joint": 150.0,
    "waist_yaw_joint": 150.0,
    "left_shoulder_pitch_joint": 65.0,
    "left_shoulder_roll_joint": 65.0,
    "left_shoulder_yaw_joint": 65.0,
    "left_elbow_joint": 30.0,
    "left_wrist_yaw_joint": 6.4,
    "left_wrist_pitch_joint": 6.4,
    "left_wrist_roll_joint": 6.4,
    "right_shoulder_pitch_joint": 65.0,
    "right_shoulder_roll_joint": 65.0,
    "right_shoulder_yaw_joint": 65.0,
    "right_elbow_joint": 30.0,
    "right_wrist_yaw_joint": 6.4,
    "right_wrist_pitch_joint": 6.4,
    "right_wrist_roll_joint": 6.4,
}


ct_scale = {
    "left_hip_pitch_joint": 0.227,
    "left_hip_roll_joint": 0.0838,
    "left_hip_yaw_joint": 0.0529,
    "left_knee_joint": 0.227,
    "left_ankle_pitch_joint": 0.0567,
    "left_ankle_roll_joint": 0.0567,
    "right_hip_pitch_joint": 0.227,
    "right_hip_roll_joint": 0.0838,
    "right_hip_yaw_joint": 0.0529,
    "right_knee_joint": 0.227,
    "right_ankle_pitch_joint": 0.0567,
    "right_ankle_roll_joint": 0.0567,
    "waist_roll_joint": 0.05294,
    "waist_pitch_joint": 0.05294,
    "waist_yaw_joint": 0.05294,
    "left_shoulder_pitch_joint": 0.0592,
    "left_shoulder_roll_joint": 0.0592,
    "left_shoulder_yaw_joint": 0.063,
    "left_elbow_joint": 0.063,
    "left_wrist_yaw_joint": 0.063,
    "left_wrist_pitch_joint": 0.063,
    "left_wrist_roll_joint": 0.063,
    "right_shoulder_pitch_joint": 0.0592,
    "right_shoulder_roll_joint": 0.0592,
    "right_shoulder_yaw_joint": 0.063,
    "right_elbow_joint": 0.063,
    "right_wrist_yaw_joint": 0.063,
    "right_wrist_pitch_joint": 0.063,
    "right_wrist_roll_joint": 0.063,
}


gear_ratio = {
    "left_hip_pitch_joint": 7,
    "left_hip_roll_joint": 31,
    "left_hip_yaw_joint": 51,
    "left_knee_joint": 7,
    "left_ankle_pitch_joint": 30,
    "left_ankle_roll_joint": 30,
    "right_hip_pitch_joint": 7,
    "right_hip_roll_joint": 31,
    "right_hip_yaw_joint": 51,
    "right_knee_joint": 7,
    "right_ankle_pitch_joint": 30,
    "right_ankle_roll_joint": 30,
    "waist_roll_joint": 51,
    "waist_pitch_joint": 51,
    "waist_yaw_joint": 51,
    "left_shoulder_pitch_joint": 51,
    "left_shoulder_roll_joint": 51,
    "left_shoulder_yaw_joint": 51,
    "left_elbow_joint": 51,
    "left_wrist_yaw_joint": 51,
    "left_wrist_pitch_joint": 51,
    "left_wrist_roll_joint": 51,
    "right_shoulder_pitch_joint": 51,
    "right_shoulder_roll_joint": 51,
    "right_shoulder_yaw_joint": 51,
    "right_elbow_joint": 51,
    "right_wrist_yaw_joint": 51,
    "right_wrist_pitch_joint": 51,
    "right_wrist_roll_joint": 51,
}

for name, torque_limit in torque_limit.items():
    current_limit = torque_limit / gear_ratio[name] / ct_scale[name]
    print(f"{name}: {current_limit}")
